### PR TITLE
Banner-wrap-text-corrected

### LINKED ISSUE #6: The Banner text is bumping and not coming in one line in mobile devices.
DESCRIPTION: The Banner text is bumping and not coming in one line in mobile . 
STEPS TO REPRODUCE:
1) Open the website in mobile phones (screen size -400 to 500 px). 
2) Clearly the problem can be noticed. 
Screenshot_2023-10-01-20-02-45-701_com android chrome

I will work on this issue to rectify the texts and improve the user experience.

### PR DESCRIPTION
**Pull request by Abhishek-465**
fixes #6 

I have fixed the issue.

SCREENSHOT:
Screenshot (17)

### CODE REVIEW

**Comment by Abhishek-465** [comment]
@lazyjinchuriki  Why your project is showing non participating in Hactoberfest?

**Comment by lazyjinchuriki** [comment]
> @lazyjinchuriki  Why your project is showing non participating in Hactoberfest? 

I don't know what you mean. Can you please elaborate.

**Comment by Abhishek-465** [comment]
@lazyjinchuriki  You have the Hactoberfest label and Hactoberfest-accepted label on this project. But then also in the Hactoberfest website it is showing like this. 

Screenshot_2023-10-03-00-24-14-506_com android chrome

**Comment by lazyjinchuriki** [comment]
> @lazyjinchuriki  You have the Hactoberfest label and Hactoberfest-accepted label on this project. But then also in the Hactoberfest website it is showing like this. 
> 
> Screenshot_2023-10-03-00-24-14-506_com android chrome
> 

I don't know what seems to be the problem.
Do you have some idea?

**Pull request merged**
